### ISSUE TITLE
Settings support

### ISSUE THREAD

**Issue by madisparn** [shinamicorp/gradle-codeartifact-login#1]
Hello, 

Would it be possible to add support to apply the plugin in settings.gradle.kts file so other plugins can be loaded from codeartifact repository?

**Comment by jasonxh** [comment]
Not that it's infeasible, but the circular dependency makes it challenging to reconcile with the current two-phased design:
- The CodeArtifact info is configured in the project and the tokens are generated by running the `codeArtifactLogin` task.
- However, if the project uses plugins from a CodeArtifact repository, it needs to be able to access the repository as part of evaluation. No task can be run before that, including `codeArtifactLogin`. Back to the first point.

May need some major rework in token generation to support this.

**Comment by madisparn** [comment]
Yes, I will try to find another solution.
